name: Conventional CI

on:
  push:
    branches: [master]
    paths:
      - "webui/**"
      - ".github/workflows/webui-ci.yml"
  pull_request:
    branches: [master]
    paths:
      - "webui/**"
      - ".github/workflows/webui-ci.yml"

jobs:
  conventional-ci:
    uses: so1ve/workflows/.github/workflows/conventional-ci.yml@v1
    with:
      skip-test: true
      working-directory: webui
